// ChineseChessActiveX.idl: ActiveX 控件项目的类型库源。

// 此文件将由 MIDL 编译器工具处理以
// 生成类型库(ChineseChessActiveX.tlb)，该类型库将成为
// ChineseChessActiveX.ocx。

#include <olectl.h>
#include <idispids.h>

[ uuid(80e92be0-a67b-421b-8ef7-8f42414880c0), version(1.0),
  helpfile("中国象棋控件.hlp"),
  helpstring("中国象棋控件"),  /*显示在引用列表框中*/
  control ]
library ChineseChessActiveXLib
{
	importlib(STDOLE_TLB);
	importlib(STDTYPE_TLB);

	//棋盘布局:详见《象棋竞赛规则(2011)》第一章 第1条
	typedef enum  _ENUM_BoardLayout {
		NoQi = 0,
		OnlyTopBlack = 1,
		OnlyBottomRed = 2,
		SwapRedBetweenBlack = 4,
		OnlyTopRed = OnlyTopBlack | SwapRedBetweenBlack,
		OnlyBottomBlack = OnlyBottomRed | SwapRedBetweenBlack,
		TopBlackAndBottomRed = OnlyTopBlack | OnlyBottomRed,
		TopRedAndBottomBlack = TopBlackAndBottomRed | SwapRedBetweenBlack
	} ENUM_BoardLayout;

	typedef enum _ENUM_QiZi {
		RShuai = 1,             //红帅
		RShi = 2,               //红仕
		RXiang = 3,             //红相
		RMa = 4,                //红马
		RChe = 5,               //红车
		RPao = 6,               //红炮
		RBing = 7,              //红兵
		NoQiZi = 0,             //无子
		BShuai = 0x8 | RShuai,  //黑帅
		BShi = 0x08 | RShi,     //黑仕
		BXiang = 0x08 | RXiang, //黑相
		BMa = 0x08 | RMa,       //黑马
		BChe = 0x08 | RChe,     //黑车
		BPao = 0x08 | RPao,     //黑炮
		BBing = 0x08 | RBing    //黑兵
	} ENUM_QiZi;

	//  CChineseChessActiveXCtrl 的主调度接口
	[ 
		uuid(7192fb6d-7455-4da8-b3ac-645dd60557f3),
		helpstring("中国象棋控件 - 分发接口")
	]
	dispinterface _DChineseChessActiveX
	{
		properties:
			[id(1), helpstring("棋盘颜色")] OLE_COLOR QiPangColor;
			[id(2), helpstring("棋盘提示框颜色")] OLE_COLOR TiShiBoxColor;
			[id(3), helpstring("棋盘布局")] ENUM_BoardLayout BoardLayout;
			[id(4), helpstring("允许提示音")] VARIANT_BOOL EnablePromptSound;
			[id(5), helpstring("允许提示消息")] VARIANT_BOOL EnablePromptMessage;
			[id(11), helpstring("设置红方名字")] BSTR RedName;
			[id(12), helpstring("设置黑方名字")] BSTR BlackName;
			[id(13), helpstring("设置开始时间")] LONG StartTime;
			[id(14), helpstring("设置结束时间")] LONG EndTime;
			[id(15), helpstring("设置棋局标签")] BSTR GameTags;

		methods:
			[id(DISPID_ABOUTBOX)] void AboutBox();
			[id(6), helpstring("走棋")] VARIANT_BOOL GoChess(SHORT i, SHORT j);
			[id(7), helpstring("保存棋局")] VARIANT_BOOL SaveChessGame(BSTR szFile);
			[id(8), helpstring("加载棋局")] VARIANT_BOOL LoadChessGame(BSTR szFile);
			[id(9), helpstring("下一步")] VARIANT_BOOL NextStep();
			[id(10), helpstring("上一步")] VARIANT_BOOL PreviouStep();
	};

	//  CChineseChessActiveXCtrl 的事件调度接口

	[ 
		uuid(0850de98-fc76-4b94-9bbe-e2e59e0fe0ea),
		helpstring("中国象棋控件 - 事件接口")
	]
	dispinterface _DChineseChessActiveXEvents
	{
		properties:
			//  事件接口没有任何属性

		methods:
			[id(1)] void EventGoChess(SHORT i, SHORT j, LONG qz);
	};

	//  CChineseChessActiveXCtrl 的类信息
	[
		uuid(e4e060cb-a3aa-4278-b1ed-ce5020c42ec7),
		helpstring("中国象棋控件")
	]
	coclass ChineseChessActiveX
	{
		[default] dispinterface _DChineseChessActiveX;
		[default, source] dispinterface _DChineseChessActiveXEvents;
	};

};
