name: android

on:
  workflow_call:
    outputs:
      name:
        description: "The artifact name"
        value: ${{ jobs.build_android.outputs.name }}

jobs:
  build_android:

    strategy:
      matrix:
        BUILD_TYPE: [Release]
        qt_arch: [android_arm64_v8a, android_armv7, android_x86_64]
        qt_version: [6.5.1]
        include:
          - BUILD_TYPE: Release
            qt_arch: android_arm64_v8a
            qt_version: 6.5.1
            VCPKG_TARGET_TRIPLET: arm-android

          - BUILD_TYPE: Release
            qt_arch: android_armv7
            qt_version: 6.5.1
            VCPKG_TARGET_TRIPLET: arm-android

          - BUILD_TYPE: Release
            qt_version: 6.5.1
            qt_arch: android_x86_64 
            VCPKG_TARGET_TRIPLET: x64-android

    runs-on: ubuntu-latest

    env:
      artifact_name: build_android
      SOURCE_DIR:  ${{github.workspace}}/.cache/source
      TOOSL_DIR:   ${{github.workspace}}/.cache/tools
      INSTALL_DIR: ${{github.workspace}}/.cache/install_${{matrix.BUILD_TYPE}}
      ANDROID_PLATFORM: android-23
      ANDROID_NATIVE_API_LEVEL: 23
      ChineseChessControl_VERSION: "v2.0.11"
      VCPKGGITCOMMITID: d765306b074717dea8dc1c4723e1b025acb61c2d
      qt_modules: 'qtimageformats qtmultimedia qtscxml qtwebchannel qtwebsockets qtwebview'

    # Map the job outputs to step outputs
    outputs:
      name: ${{ env.artifact_name }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: make directory
        run: |
          cmake -E make_directory ${{env.SOURCE_DIR}}
          cmake -E make_directory ${{env.TOOSL_DIR}}
          cmake -E make_directory ${{env.INSTALL_DIR}}
          cmake -E make_directory ${{github.workspace}}/build

      - name: Cache Qt
        #if: false
        id: cache-qt
        uses: actions/cache@v1  # not v2!
        with:
          path: ${{env.TOOSL_DIR}}/qt
          key: qt${{matrix.qt_version}}_${{matrix.qt_arch}}

      - name: Install Qt of gcc_64
        uses: jurplel/install-qt-action@v3.2.1
        with:
          dir: '${{env.TOOSL_DIR}}/qt' # optional
          version: '${{matrix.qt_version}}'
          #host: 'linux'
          target: 'desktop'
          arch: 'gcc_64'
          set-env: false
          cached: '${{ steps.cache-qt.outputs.cache-hit }}' # optional, default is false

      - name: Install Qt of android
        uses: jurplel/install-qt-action@v3.2.1
        with:
          # Directory to install Qt
          dir: '${{env.TOOSL_DIR}}/qt' # optional
          # Version of Qt to install
          version: '${{matrix.qt_version}}'
          # Host platform
          #host: linux # optional
          # Target platform for build
          target: 'android' # optional, default is desktop
          # Architecture for Windows/Android
          arch: '${{matrix.qt_arch}}' # optional
          # Additional Qt modules to install
          modules: '${{env.qt_modules}}' # optional. See: https://ddalcino.github.io/aqt-list-server/
          # Whether or not to actually download Qt
          cached: '${{ steps.cache-qt.outputs.cache-hit }}' # optional, default is false

#    - name: run-vcpkg
#      uses: lukka/run-vcpkg@v7.4
#      with:
#        # Indicates whether to only setup vcpkg (i.e. installing it and setting the environment variables VCPKG_ROOT, RUNVCPK_VCPKG_ROOT), without installing any port.
#        #setupOnly: # optional
#        #vcpkgGitURL: https://github.com/KangLin/vcpkg.git
#        vcpkgGitCommitId: ${{env.VCPKGGITCOMMITID}}
#        vcpkgDirectory: ${{ runner.workspace }}/vcpkg/
#        # Since the cache must be invalidated when content of the vcpkg.json file changes, let's
#        # compute its hash and append this to the computed cache's key.
#        appendedCacheKey: android-qt${{matrix.qt_version}}-${{matrix.VCPKG_TARGET_TRIPLET}}-${{matrix.BUILD_TYPE}}-${{env.VCPKGGITCOMMITID}}
#        additionalCachedPaths: $VCPKG_ROOT/installed
#        vcpkgTriplet: '${{ matrix.VCPKG_TARGET_TRIPLET }}'
#        vcpkgArguments: 'zlib openssl'

      - name: Cache installed
        uses: actions/cache@v3
        id: cache-installed
        with:
          path: |
            ${{env.INSTALL_DIR}}
          key: cache-installed-android-qt${{matrix.qt_version}}-${{matrix.VCPKG_TARGET_TRIPLET}}-${{matrix.BUILD_TYPE}}

      - name: git clone RabbitCommon
        working-directory: ${{env.SOURCE_DIR}}
        run: |
          git clone https://github.com/KangLin/RabbitCommon.git

      - name: build ChineseChessControl
        working-directory: ${{github.workspace}}/build
        env:
          STOREPASS: ${{secrets.STOREPASS}}
          RabbitCommon_DIR: ${{env.SOURCE_DIR}}/RabbitCommon
        run: |
          sudo chmod 777 ${Qt6_DIR}/bin/qt-cmake
          ${Qt6_DIR}/bin/qt-cmake .. \
              -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}} \
              -DQT_HOST_PATH=${Qt6_DIR}/../gcc_64 \
              -DANDROID_PLATFORM=${{env.ANDROID_PLATFORM}} \
              -DANDROID_NATIVE_API_LEVEL=${{env.ANDROID_NATIVE_API_LEVEL}} \
              -DQt6LinguistTools_DIR=${Qt6_DIR}/../gcc_64/lib/cmake/Qt6LinguistTools \
              -DCMAKE_INSTALL_PREFIX=`pwd`/install
          cmake --build . --config ${{matrix.BUILD_TYPE}}  --target all
          cmake --build . --config ${{matrix.BUILD_TYPE}}  --target install
          APK_FILE=`find . -name "android-*.apk"`
          cp $APK_FILE ChineseChessControl_${{env.ChineseChessControl_VERSION}}_${{matrix.qt_arch}}_qt${{matrix.qt_version}}_${{matrix.BUILD_TYPE}}.apk
          7z a ChineseChessControl_${{env.ChineseChessControl_VERSION}}_${{matrix.qt_arch}}_qt${{matrix.qt_version}}_${{matrix.BUILD_TYPE}}.zip install/*

      - name: Update artifact
        #if: ${{ matrix.BUILD_TYPE == 'Release' }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.artifact_name }}
          path: |
            ${{github.workspace}}/build/ChineseChessControl_${{env.ChineseChessControl_VERSION}}_${{matrix.qt_arch}}_qt${{matrix.qt_version}}_${{matrix.BUILD_TYPE}}.zip
            ${{github.workspace}}/build/ChineseChessControl_${{env.ChineseChessControl_VERSION}}_${{matrix.qt_arch}}_qt${{matrix.qt_version}}_${{matrix.BUILD_TYPE}}.apk
     
