name: build

env:
  artifact_path: artifact_path
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ChineseChessControl_VERSION: "v2.0.7"
on: 
  push:
  
jobs:
  ubuntu:
    uses: ./.github/workflows/ubuntu.yml

  msvc:
    uses: ./.github/workflows/msvc.yml

  mingw:
    uses: ./.github/workflows/mingw.yml

  macos:
    uses: ./.github/workflows/macos.yml

  android:
    uses: ./.github/workflows/android.yml
  
  doxygen:
    uses: ./.github/workflows/doxygen.yml
#    if: ${{ startsWith(github.ref, 'refs/tags/') }}

  deploy:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    needs: [ubuntu, msvc, macos, android, doxygen]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Download ubuntu
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.ubuntu.outputs.name }}
          path: ${{ env.artifact_path }}

      - name: Download msvc
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.msvc.outputs.name }}
          path: ${{ env.artifact_path }}

      - name: Download macos
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.macos.outputs.name }}
          path: ${{ env.artifact_path }}

      - name: Download android
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.android.outputs.name }}
          path: ${{ env.artifact_path }}

      - name: Download doxygen
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.doxygen.outputs.name }}
          path: ${{ env.artifact_path }}

      - name: Make note file
        run: |
          cd ${{ env.artifact_path }}
          echo "[:cn: 修改日志](https://github.com/KangLin/ChineseChessControl/blob/${{env.ChineseChessControl_VERSION}}/ChangeLog_zh_CN.md)" > ${{github.workspace}}/Release.md
          echo "" >> ${{github.workspace}}/Release.md
          echo "文件签名:" >> ${{github.workspace}}/Release.md
          for file in *
          do
              echo $file
              if [ -f $file ]; then
                  md5sum $file > $file.md5sum
                  cat $file.md5sum >> ${{github.workspace}}/Release.md
              fi
          done

      - name: Upload To Github Release
        run: |
          gh release create ${{ github.ref_name }} --title ${{ github.ref_name }} --notes-file ${{github.workspace}}/Release.md
          gh release upload ${{ github.ref_name }} ${{github.workspace}}/${{ env.artifact_path }}/*
