name: build

env:
  artifact_path: artifact_path

on: 
  push:
  
jobs:
  build_linux:
    uses: ./.github/workflows/ubuntu.yml

  build_windows:
    uses: ./.github/workflows/msvc.yml

  deploy:
    runs-on: ubuntu-latest
    needs: [build_linux, build_windows]
    steps:
      - name: Download linux
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.build_linux.outputs.name }}
          path: ${{ env.artifact_path }}

      - name: Download windows
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.build_windows.outputs.name }}
          path: ${{ env.artifact_path }}

      - name: deploy
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          echo "Deploy ......"
          ls -R ${{ env.artifact_path }}
