name: build

env:
  artifact_path: artifact_path

on: 
  push:
  
jobs:
  ubuntu:
    uses: ./.github/workflows/ubuntu.yml

  msvc:
    uses: ./.github/workflows/msvc.yml

  mingw:
    uses: ./.github/workflows/mingw.yml

  macos:
    uses: ./.github/workflows/macos.yml

  deploy:
    runs-on: ubuntu-latest
    needs: [ubuntu, msvc, macos]
    #if: ${{ startsWith(github.ref, 'refs/tags/') }}
    steps:
      - name: Download ubuntu
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.ubuntu.outputs.name }}
          path: ${{ env.artifact_path }}

      - name: Download msvc
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.msvc.outputs.name }}
          path: ${{ env.artifact_path }}

      - name: Download macos
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.macos.outputs.name }}
          path: ${{ env.artifact_path }}

      - name: deploy
        #if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          echo "Deploy ......"
          ls -R ${{ env.artifact_path }}
