name: mingw

on:
  workflow_call:
    outputs:
      name:
        description: "The artifact name"
        value: ${{ jobs.build_mingw.outputs.name }}

jobs:
  build_mingw:

    strategy:
      matrix:
        BUILD_TYPE: [Release, Debug]

    defaults:
      run:
        shell: cmd
        
    runs-on: windows-latest
    env:
      BUILD_TYPE:  ${{ matrix.BUILD_TYPE }}
      SOURCE_DIR:  ${{github.workspace}}\.cache\source
      TOOSL_DIR:   ${{github.workspace}}\.cache\tools
      INSTALL_DIR: ${{github.workspace}}\.cache\install
      artifact_name: build_mingw
      ChineseChessControl_VERSION: "v2.0.12"

    # Map the job outputs to step outputs
    outputs:
      name: ${{ env.artifact_name }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Make directories
        run: |
          cmake -E make_directory ${{env.SOURCE_DIR}}
          cmake -E make_directory ${{env.TOOSL_DIR}}
          cmake -E make_directory ${{env.INSTALL_DIR}}
          cmake -E make_directory ${{github.workspace}}/build

      - name: Cache installed
        uses: actions/cache@v3
        id: cache-installed
        with:
          path: |
            ${{env.INSTALL_DIR}}
          key: install_mingw_${{matrix.BUILD_TYPE}}

      - name: pacman
        env:
          PATH: C:\msys64\usr\bin
        run: | 
          C:\msys64\usr\bin\pacman.exe -S --noconfirm ^
              mingw-w64-x86_64-cmake ^
              mingw-w64-x86_64-make ^
              mingw-w64-x86_64-nsis ^
              mingw-w64-x86_64-gcc ^
              mingw-w64-x86_64-qt5 ^
              mingw-w64-x86_64-qt5-multimedia ^
              mingw-w64-x86_64-qt5-svg ^
              mingw-w64-x86_64-qtwebkit ^
              mingw-w64-x86_64-zlib ^
              mingw-w64-x86_64-7zip ^
              git base-devel

      - name: git clone RabbitCommon
        working-directory: ${{env.SOURCE_DIR}}
        run: |
          git clone https://github.com/KangLin/RabbitCommon.git

      - name: build ChineseChessControl
        working-directory: ${{github.workspace}}/build
        env:
          RabbitCommon_DIR: ${{env.SOURCE_DIR}}/RabbitCommon
          MSYSTEM: MINGW64
          PATH: C:\msys64\mingw64\bin;C:\msys64\usr\bin
        run: |
          cmake ${{github.workspace}} -G"MinGW Makefiles" ^
              -DCMARK_SHARED=OFF ^
              -DCMARK_TESTS=OFF ^
              -DCMARK_STATIC=ON ^
              -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}} ^
              -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/build/install ^
              -DCMAKE_PREFIX_PATH=${{env.INSTALL_DIR}} ^
              -DINSTALL_QT=ON ^
              -DBUILD_APP=ON
          cmake --build . --config ${{ matrix.BUILD_TYPE }}

      - name: Package
        working-directory: ${{github.workspace}}/build
        if: ${{ matrix.BUILD_TYPE == 'Release' }}
        run: |
          cmake --build . --config ${{ matrix.BUILD_TYPE }} --target package

#      - name: Update artifact 
#        uses: actions/upload-artifact@v3
#        if: false
#        with:
#          name: rabbitremotecontrol_${{ matrix.os }}
#          path: |
#            ${{github.workspace}}\build\chinesechesscontrol_${{env.ChineseChessControl_VERSION}}_*_setup.exe
