name: msvc

on:
  workflow_call:
    outputs:
      name:
        description: "The artifact name"
        value: ${{ jobs.build_msvc.outputs.name }}

jobs:
  build_msvc:

    strategy:
      matrix:
        BUILD_TYPE: [Release, Debug]
        qt_version: [6.6.2, 5.15.2, 5.12.12]
        include:
          - qt_version: 6.6.2
            triplet: x64-windows
            VCPKG_PLATFORM_TOOLSET: v142
            qt_arch: win64_msvc2019_64
            CMAKE_GENERATOR_PLATFORM: x64
            qt_modules: qtmultimedia qtimageformats qtscxml qtwebchannel qtwebsockets qtwebview qtpositioning

          - qt_version: 5.15.2
            triplet: x64-windows
            VCPKG_PLATFORM_TOOLSET: v142
            VCPKG_MANIFEST_DIR: "\\vcpkg\\manifests"
            qt_arch: win64_msvc2019_64
            CMAKE_GENERATOR_PLATFORM: x64

          - qt_version: 5.12.12
            triplet: x86-windows
            VCPKG_PLATFORM_TOOLSET: v141
            VCPKG_MANIFEST_DIR: "\\vcpkg\\manifests"
            qt_arch: win32_msvc2017
            CMAKE_GENERATOR_PLATFORM: Win32

    runs-on: windows-latest

    env:
      ChineseChessControl_VERSION: "v2.0.11"
      artifact_name: build_msvc
      SOURCE_DIR:  ${{github.workspace}}\.cache\source
      TOOSL_DIR:   ${{github.workspace}}\.cache\tools
      INSTALL_DIR: ${{github.workspace}}\.cache\install
      CMAKE_GENERATOR: "Visual Studio 17 2022"
      CMAKE_GENERATOR_PLATFORM: ${{matrix.CMAKE_GENERATOR_PLATFORM}}
      VCPKG_PLATFORM_TOOLSET: ${{matrix.VCPKG_PLATFORM_TOOLSET}}
      VCPKG_MANIFEST_DIR: "${{github.workspace}}${{matrix.VCPKG_MANIFEST_DIR}}"
      VCPKGGITCOMMITID: a1a1cbc975abf909a6c8985a6a2b8fe20bbd9bd6
      qt_modules: qtwebengine ${{matrix.qt_modules}}

    # Map the job outputs to step outputs
    outputs:
      name: ${{ env.artifact_name }}
  
    defaults:
      run:
        shell: cmd

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: make directory
        run: |
          cmake -E make_directory ${{env.SOURCE_DIR}}
          cmake -E make_directory ${{env.TOOSL_DIR}}
          cmake -E make_directory ${{env.INSTALL_DIR}}
          cmake -E make_directory ${{github.workspace}}/build
          cmake -E make_directory ${{github.workspace}}/build_app
          cmake -E make_directory ${{github.workspace}}/build_package

      - name: Cache installed
        uses: actions/cache@v3
        id: cache-installed
        with:
          path: |
            ${{env.INSTALL_DIR}}
          key:  install_${{matrix.qt_arch}}_qt${{matrix.qt_version}}_${{matrix.BUILD_TYPE}}

      - name: run vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: ${{env.VCPKGGITCOMMITID}}
          vcpkgDirectory: ${{runner.workspace}}/vcpkg/

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          dir: '${{env.TOOSL_DIR}}/qt' # optional
          version: '${{matrix.qt_version}}' # optional, default is 5.15.2
          arch: '${{matrix.qt_arch}}' # optional
          modules: '${{env.qt_modules}}' # optional. See: https://ddalcino.github.io/aqt-list-server/
          cache: true
          cache-key-prefix: cached_qt
 
      - name: git clone RabbitCommon
        working-directory: ${{env.SOURCE_DIR}}
        run: git clone https://github.com/KangLin/RabbitCommon.git

      - name: build ChineseChessControl
        working-directory: ${{github.workspace}}/build
        env:
          RabbitCommon_DIR: ${{env.SOURCE_DIR}}/RabbitCommon
        run: |
          cmake ${{github.workspace}} ^
              -A ${{matrix.CMAKE_GENERATOR_PLATFORM}} ^
              -T ${{matrix.VCPKG_PLATFORM_TOOLSET}} ^
              -DCMARK_SHARED=OFF ^
              -DCMARK_TESTS=OFF ^
              -DCMARK_STATIC=ON ^
              -DRABBIT_ENABLE_INSTALL_DEPENDENT=ON ^
              -DRABBIT_ENABLE_INSTALL_QT=ON ^
              -DRABBIT_ENABLE_INSTALL_TO_BUILD_PATH=OFF ^
              -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}} ^
              -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/build/install ^
              -DCMAKE_TOOLCHAIN_FILE=${{env.VCPKG_ROOT}}/scripts/buildsystems/vcpkg.cmake ^
              -DVCPKG_MANIFEST_DIR=${{env.VCPKG_MANIFEST_DIR}} ^
              -DVCPKG_VERBOSE=ON ^
              -DX_VCPKG_APPLOCAL_DEPS_INSTALL=ON ^
              -DVCPKG_APPLOCAL_DEPS=ON
          cmake --build . --config ${{matrix.BUILD_TYPE}}

      - name: Package program
        if: ${{ matrix.BUILD_TYPE == 'Release' }}
        working-directory: ${{github.workspace}}\build
        run: |
          cmake --install . --config ${{matrix.BUILD_TYPE}} --component=MFCApplications
          cmake --install . --config ${{matrix.BUILD_TYPE}} --component=MFCRuntime
          cmake --install . --config ${{matrix.BUILD_TYPE}} --component=QtApplications
          cmake --install . --config ${{matrix.BUILD_TYPE}} --component=QtRuntime
          cmake --install . --config ${{matrix.BUILD_TYPE}} --component=Runtime
          cmake --install . --config ${{matrix.BUILD_TYPE}} --component=DependLibraries
          copy /Y ${{env.INSTALL_DIR}}\bin\*.dll install\bin
          copy /Y ${{env.INSTALL_DIR}}\lib\*.dll install\bin
          copy /Y ${{env.RUNVCPKG_VCPKG_ROOT}}\installed\${{env.RUNVCPKG_VCPKG_TRIPLET_OUT}}\bin\*.dll install\bin
          makensis Install.nsi
          RENAME ChineseChessControl_${{env.ChineseChessControl_VERSION}}_Setup.exe ChineseChessControl_${{env.ChineseChessControl_VERSION}}_${{matrix.qt_arch}}_Qt${{matrix.qt_version}}_${{matrix.BUILD_TYPE}}_Setup.exe 

      - name: Package develop library
        working-directory: ${{github.workspace}}\build
        run: |
          cmake --install . --config ${{matrix.BUILD_TYPE}} --prefix=%CD%\install_develop --component=MFCDevelopment
          cmake --install . --config ${{matrix.BUILD_TYPE}} --prefix=%CD%\install_develop --component=QtDevelopment
          cmake --install . --config ${{matrix.BUILD_TYPE}} --prefix=%CD%\install_develop --component=Development
          7z a ChineseChessControl_${{env.ChineseChessControl_VERSION}}_${{matrix.qt_arch}}_Qt${{matrix.qt_version}}_${{matrix.BUILD_TYPE}}_Develop.zip %CD%\install_develop\.

      - name: Update artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.artifact_name }}
          path: |
            ${{github.workspace}}\build\ChineseChessControl_*.exe
            ${{github.workspace}}\build\ChineseChessControl_${{env.ChineseChessControl_VERSION}}_${{matrix.qt_arch}}_Qt${{matrix.qt_version}}_${{matrix.BUILD_TYPE}}_Develop.zip
